"""
This type stub file was generated by pyright.
"""

import os

import streamlit as st
import streamlit.components.v1 as components

_RELEASE = ...
if not _RELEASE:
    _component_func = ...
else:
    parent_dir = ...
    build_dir = ...
    _component_func = ...

def st_autorefresh(interval=..., *, limit=..., debounce=..., key=...):  # -> int:
    """Create an autorefresh instance to trigger a refresh of the application

    Parameters
    ----------
    interval: int
        Amount of time in milliseconds to
    limit: int or None
        Amount of refreshes to allow. If none, it will refresh infinitely.
        While infinite refreshes sounds nice, it will continue to utilize
        computing resources.
    debounce: boolean
        Whether to delay the autorefresh when user interaction occurs.
        Defaults to True in order to avoid refreshes interfering with
        interaction effects on scripts.
    key: str or None
        An optional key that uniquely identifies this component. If this is
        None, and the component's arguments are changed, the component will
        be re-mounted in the Streamlit frontend and lose its current state.

    Returns
    -------
    int
        Number of times the refresh has been triggered or max value of int
    """
    ...

if not _RELEASE:
    secs = ...
    should_debounce = ...
    count = ...
