"""
This type stub file was generated by pyright.
"""

HOSTNAME = ...
PID = ...
class EventBuffer:
    def __init__(self) -> None:
        ...
    
    def push(self, type, count=...): # -> None:
        ...
    
    def get_and_clear(self): # -> list[Any]:
        ...
    


class InstrumentedServer:
    def __init__(self, sio, auth=..., mode=..., read_only=..., server_id=..., namespace=..., server_stats_interval=...) -> None:
        """Instrument the Socket.IO server for monitoring with the `Socket.IO
        Admin UI <https://socket.io/docs/v4/admin-ui/>`_.
        """
        ...
    
    def instrument(self): # -> None:
        ...
    
    def uninstrument(self): # -> None:
        ...
    
    def admin_connect(self, sid, environ, client_auth): # -> None:
        ...
    
    def admin_emit(self, _, namespace, room_filter, event, *data): # -> None:
        ...
    
    def admin_enter_room(self, _, namespace, room, room_filter=...): # -> None:
        ...
    
    def admin_leave_room(self, _, namespace, room, room_filter=...): # -> None:
        ...
    
    def admin_disconnect(self, _, namespace, close, room_filter=...): # -> None:
        ...
    
    def shutdown(self): # -> None:
        ...
    
    def serialize_socket(self, sid, namespace, eio_sid=...): # -> dict[str, Any]:
        ...
    


