"""
This type stub file was generated by pyright.
"""

HOSTNAME = ...
PID = ...

class InstrumentedAsyncServer:
    def __init__(
        self,
        sio,
        auth=...,
        namespace=...,
        read_only=...,
        server_id=...,
        mode=...,
        server_stats_interval=...,
    ) -> None:
        """Instrument the Socket.IO server for monitoring with the `Socket.IO
        Admin UI <https://socket.io/docs/v4/admin-ui/>`_.
        """
        ...

    def instrument(self):  # -> None:
        ...
    def uninstrument(self):  # -> None:
        ...
    async def admin_connect(self, sid, environ, client_auth):  # -> None:
        ...
    async def admin_emit(self, _, namespace, room_filter, event, *data):  # -> None:
        ...
    async def admin_enter_room(self, _, namespace, room, room_filter=...):  # -> None:
        ...
    async def admin_leave_room(self, _, namespace, room, room_filter=...):  # -> None:
        ...
    async def admin_disconnect(self, _, namespace, close, room_filter=...):  # -> None:
        ...
    async def shutdown(self):  # -> None:
        ...
    def serialize_socket(self, sid, namespace, eio_sid=...):  # -> dict[str, Any]:
        ...
