"""
This type stub file was generated by pyright.
"""

class BaseNamespace:
    def __init__(self, namespace=...) -> None:
        ...
    
    def is_asyncio_based(self): # -> Literal[False]:
        ...
    


class BaseServerNamespace(BaseNamespace):
    def __init__(self, namespace=...) -> None:
        ...
    
    def rooms(self, sid, namespace=...):
        """Return the rooms a client is in.

        The only difference with the :func:`socketio.Server.rooms` method is
        that when the ``namespace`` argument is not given the namespace
        associated with the class is used.
        """
        ...
    


class BaseClientNamespace(BaseNamespace):
    def __init__(self, namespace=...) -> None:
        ...
    


