"""
This type stub file was generated by pyright.
"""

class SocketIOError(Exception):
    ...


class ConnectionError(SocketIOError):
    ...


class ConnectionRefusedError(ConnectionError):
    """Connection refused exception.

    This exception can be raised from a connect handler when the connection
    is not accepted. The positional arguments provided with the exception are
    returned with the error packet to the client.
    """
    def __init__(self, *args) -> None:
        ...
    


class TimeoutError(SocketIOError):
    ...


class BadNamespaceError(SocketIOError):
    ...


class DisconnectedError(SocketIOError):
    ...


