"""
This type stub file was generated by pyright.
"""

from . import packet

class MsgPackPacket(packet.Packet):
    uses_binary_events = ...
    def encode(self):
        """Encode the packet for transmission."""
        ...
    
    def decode(self, encoded_packet): # -> None:
        """Decode a transmitted package."""
        ...
    


