"""
This type stub file was generated by pyright.
"""

from .manager import Manager

class PubSubManager(Manager):
    """Manage a client list attached to a pub/sub backend.

    This is a base class that enables multiple servers to share the list of
    clients, with the servers communicating events through a pub/sub backend.
    The use of a pub/sub backend also allows any client connected to the
    backend to emit events addressed to Socket.IO clients.

    The actual backends must be implemented by subclasses, this class only
    provides a pub/sub generic framework.

    :param channel: The channel name on which the server sends and receives
                    notifications.
    """
    name = ...
    def __init__(self, channel=..., write_only=..., logger=...) -> None:
        ...
    
    def initialize(self): # -> None:
        ...
    
    def emit(self, event, data, namespace=..., room=..., skip_sid=..., callback=..., to=..., **kwargs): # -> None:
        """Emit a message to a single client, a room, or all the clients
        connected to the namespace.

        This method takes care or propagating the message to all the servers
        that are connected through the message queue.

        The parameters are the same as in :meth:`.Server.emit`.
        """
        ...
    
    def can_disconnect(self, sid, namespace): # -> bool | None:
        ...
    
    def disconnect(self, sid, namespace=..., **kwargs): # -> None:
        ...
    
    def enter_room(self, sid, namespace, room, eio_sid=...): # -> None:
        ...
    
    def leave_room(self, sid, namespace, room): # -> None:
        ...
    
    def close_room(self, room, namespace=...): # -> None:
        ...
    


